export const departments = [
  {
    id: "general",
    name: "General Medicine",
    icon: "Stethoscope",
    description: "General health checkups and consultations",
    waitTime: "15 mins",
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    icon: "Baby",
    description: "Child healthcare and vaccinations",
    waitTime: "20 mins",
  },
  { id: "orthopedics", name: "Orthopedics", icon: "Bone", description: "Bone and joint care", waitTime: "25 mins" },
  {
    id: "cardiology",
    name: "Cardiology",
    icon: "Heart",
    description: "Heart and cardiovascular health",
    waitTime: "30 mins",
  },
  {
    id: "dermatology",
    name: "Dermatology",
    icon: "Sparkles",
    description: "Skin care and treatments",
    waitTime: "20 mins",
  },
  {
    id: "ophthalmology",
    name: "Ophthalmology",
    icon: "Eye",
    description: "Eye care and vision tests",
    waitTime: "15 mins",
  },
]

export const doctors = [
  {
    id: "d1",
    name: "Dr. Priya Sharma",
    department: "general",
    experience: "15 years",
    rating: 4.8,
    available: true,
    image: "/indian-female-doctor-portrait.jpg",
  },
  {
    id: "d2",
    name: "Dr. Rajesh Kumar",
    department: "general",
    experience: "12 years",
    rating: 4.7,
    available: true,
    image: "/indian-male-doctor-portrait.jpg",
  },
  {
    id: "d3",
    name: "Dr. Anita Desai",
    department: "pediatrics",
    experience: "10 years",
    rating: 4.9,
    available: true,
    image: "/indian-female-pediatrician-portrait.jpg",
  },
  {
    id: "d4",
    name: "Dr. Vikram Singh",
    department: "orthopedics",
    experience: "18 years",
    rating: 4.6,
    available: false,
    image: "/indian-male-orthopedic-doctor.jpg",
  },
  {
    id: "d5",
    name: "Dr. Meera Patel",
    department: "cardiology",
    experience: "20 years",
    rating: 4.9,
    available: true,
    image: "/indian-female-cardiologist.jpg",
  },
  {
    id: "d6",
    name: "Dr. Suresh Reddy",
    department: "dermatology",
    experience: "8 years",
    rating: 4.5,
    available: true,
    image: "/indian-male-dermatologist.jpg",
  },
]

export const timeSlots = [
  "09:00 AM",
  "09:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "02:00 PM",
  "02:30 PM",
  "03:00 PM",
  "03:30 PM",
  "04:00 PM",
  "04:30 PM",
  "05:00 PM",
  "05:30 PM",
  "06:00 PM",
]

export const mockQueueData = {
  currentToken: 8,
  yourToken: 12,
  totalInQueue: 15,
  estimatedWait: "20 mins",
  queue: [
    { token: 8, status: "serving", name: "Patient A" },
    { token: 9, status: "next", name: "Patient B" },
    { token: 10, status: "waiting", name: "Patient C" },
    { token: 11, status: "waiting", name: "Patient D" },
    { token: 12, status: "waiting", name: "You" },
    { token: 13, status: "waiting", name: "Patient F" },
  ],
}

export const mockPatientHistory = [
  {
    id: "v1",
    date: "2026-01-10",
    doctor: "Dr. Priya Sharma",
    department: "General Medicine",
    diagnosis: "Seasonal flu with mild fever. Prescribed rest and medication.",
    prescription: ["Paracetamol 500mg - 3 times daily", "Vitamin C - Once daily"],
    followUp: "2026-01-17",
  },
  {
    id: "v2",
    date: "2025-12-15",
    doctor: "Dr. Meera Patel",
    department: "Cardiology",
    diagnosis: "Routine heart checkup. All vitals normal. ECG shows healthy heart rhythm.",
    prescription: ["Continue regular exercise", "Low sodium diet recommended"],
    followUp: "2026-06-15",
  },
  {
    id: "v3",
    date: "2025-11-20",
    doctor: "Dr. Anita Desai",
    department: "Pediatrics",
    diagnosis: "Child vaccination - DPT booster dose administered.",
    prescription: ["Mild fever expected", "Paracetamol syrup if needed"],
    followUp: null,
  },
]

export const stats = {
  appointmentsServed: 125430,
  happyPatients: 98500,
  doctors: 45,
  clinics: 12,
}

export const doctorDashboardData = {
  todayAppointments: 24,
  queueLength: 8,
  patientsServed: 16,
  avgConsultTime: "12 mins",
  currentPatient: {
    token: 17,
    name: "Amit Patel",
    age: 45,
    gender: "Male",
    phone: "+91 98765 12345",
    symptoms: "Persistent headache for 3 days, mild fever",
    visitHistory: 3,
  },
  queue: [
    {
      token: 17,
      name: "Amit Patel",
      age: 45,
      time: "10:30 AM",
      status: "serving" as const,
      symptoms: "Headache, fever",
    },
    { token: 18, name: "Sunita Devi", age: 32, time: "10:45 AM", status: "next" as const, symptoms: "Back pain" },
    { token: 19, name: "Rahul Sharma", age: 28, time: "11:00 AM", status: "waiting" as const, symptoms: "Skin rash" },
    {
      token: 20,
      name: "Kavita Singh",
      age: 55,
      time: "11:15 AM",
      status: "waiting" as const,
      symptoms: "Diabetes checkup",
    },
    { token: 21, name: "Deepak Kumar", age: 38, time: "11:30 AM", status: "waiting" as const, symptoms: "Cough, cold" },
    { token: 22, name: "Meera Joshi", age: 42, time: "11:45 AM", status: "waiting" as const, symptoms: "Joint pain" },
  ],
  upcomingAppointments: [
    { id: "a1", patient: "Vikram Reddy", time: "02:00 PM", type: "Follow-up" },
    { id: "a2", patient: "Anjali Gupta", time: "02:30 PM", type: "New" },
    { id: "a3", patient: "Suresh Nair", time: "03:00 PM", type: "Follow-up" },
    { id: "a4", patient: "Pooja Mehta", time: "03:30 PM", type: "New" },
  ],
}
